<a href="https://colab.research.google.com/github/ValerySiccha/C8280/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

NumPy es la librería central para computación científica en Python. Proporciona un objeto de matriz multidimensional de alto rendimiento y herramientas para trabajar con estas matrices.

#### Matrices

Una matriz NumPy es una colección de valores de tipos de datos similares y está indexada por una tupla de números no negativos. El rango de la matriz es el número de dimensiones, y la forma de una matriz es una tupla de números que dan el tamaño de la matriz a lo largo de cada dimensión.


In [4]:
# Ejemplo
from __future__ import division
import time
import numpy as np


tam_vec = 1000
def lista_python():
    t1 = time.time()
    X = range(tam_vec)
    Y = range(tam_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def matriz_numpy():
    t1 = time.time()
    X = np.arange(tam_vec)
    Y = np.arange(tam_vec)
    Z = X + Y
    return time.time() - t1

# Completar

t1= lista_python()
t2= matriz_numpy()

print(t1,t2)
print(f'Numpy es en este ejemplo:{str(t1/t2)} más rápido!')

0.0003364086151123047 0.004289865493774414
Numpy es en este ejemplo:0.07841938531651198 más rápido!


In [ ]:
#import numpy
#numpy.__version__

Podemos inicializar matrices NumPy a partir de listas de Python anidadas y acceder a los elementos mediante corchetes.

In [5]:
import numpy as np

# Creamos una matriz de rango 1
a = np.array([0, 1, 2])
print (type(a))

# Imprimimos la dimension de la matriz
print (a.shape)
print (a[0])
print (a[1])
print (a[2])

# Cambiamos un elemento de un array
a[0] = 5
print (a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [6]:
# Creamos una matriz de rango 2
b = np.array([[0,1,2],[3,4,5]])
print (b.shape)
print (b)
print (b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [7]:
print ( b.shape)
print ( b[0, 0], b[0, 1], b[1, 0])

(2, 3)
0 1 3


### Creación de una matriz NumPy

NumPy también proporciona muchas funciones integradas para crear matrices. La mejor manera de aprender esto es a través de ejemplos, así que pasemos al código.

In [8]:
# Creamos una matriz 3x3 de todos ceros
a = np.zeros((3,3))
print (a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Creamos una matriz 2x2 de todos 1
b = np.ones((2,2))
print (b)

[[1. 1.]
 [1. 1.]]


In [10]:
# Creamos una matriz 3x3 constantes
c = np.full((3,3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [11]:
# Creamos una matriz 3x3 con valores aleatorios
d = np.random.random((3,3))
print (d)

[[0.65404142 0.51435886 0.96246962]
 [0.19499479 0.64318786 0.41885582]
 [0.6641798  0.63781849 0.27342852]]


In [12]:
# Creamos una matriz identidad 3x3
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# Convertir una lista en una matriz
f = np.array([2, 3, 1,0])
print(f)

[2 3 1 0]


In [ ]:
# arange() crea matrices con valores que se incrementan regularmente
# Completar

g= np.arange(1,10,2)
print(g)

[1 3 5 7 9]


In [ ]:
# Mezcla de tupla y listas
# Completar

g=np.array([(1,2,3),[4,5,6]])
print(g)

[[1 2 3]
 [4 5 6]]


In [14]:
# Crear una matriz de rango con tipo de datos flotante
i = np.arange(1, 8, dtype=np.float64)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


`linspace()`  crea matrices con un numero especifico de elementos que están espaciados por igual entre los valores inicial y final especificados

In [ ]:
# Completa

j=np.linspace(0,2,5)
print(j)

[0.  0.5 1.  1.5 2. ]


### Tipos de datos
Una matriz es una colección de elementos del mismo tipo de datos y NumPy admite y proporciona funciones integradas para construir matrices con argumentos opcionales para especificar explícitamente los tipos de datos requeridos.

In [ ]:
# Numpy escoge el tipo de datos
x = np.array([0, 1])
y = np.array([2.0, 3.0])

# Fuerza un tipo de datos en particular
z = np.array([5, 6], dtype=np.int64)
print (x.dtype, y.dtype, z.dtype)

int64 float64 int64


**Ejercicio** Completa el siguiente  código.

In [ ]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)  # matriz 1-d
x2 = np.random.randint(10, size=(5, 4))  # matriz-2d
x3 = np.random.randint(10, size=(2, 4, 5)) # matriz-3d

# Imprime los atributos : dim, shape, size, dtype, itemsize y nbytes

# Completar

print(f'La dimensión para x1 es: {x1.ndim} mientras que la de x2 es: {x2.ndim} y para x3 es: {x3.ndim}')
print(f'El shape para x1 es: {x1.shape} mientras que la de x2 es: {x2.shape} y para x3 es: {x3.shape}')
print(f'El size para x1 es: {x1.size} mientras que la de x2 es: {x2.size} y para x3 es {x3.size}')
print(f'El dtype para x1 es: {x1.dtype} mientras que la de x2 es: {x2.dtype} y para x3 es {x3.dtype}')
print(f'El itemsize para x1 es {x1.itemsize} mientras que la de x2 es: {x2.itemsize} y para x3 es: {x3.itemsize}')
print(f'El nbytes para x1 es: {x1.nbytes} mientras que la de x2 es: {x2.nbytes} y para x3 es: {x3.nbytes}')

La dimensión para x1 es: 1 mientras que la de x2 es: 2 y para x3 es: 3
El shape para x1 es: (6,) mientras que la de x2 es: (5, 4) y para x3 es: (2, 4, 5)
El size para x1 es: 6 mientras que la de x2 es: 20 y para x3 es 40
El dtype para x1 es: int64 mientras que la de x2 es: int64 y para x3 es int64
El itemsize para x1 es 8 mientras que la de x2 es: 8 y para x3 es: 8
El nbytes para x1 es: 48 mientras que la de x2 es: 160 y para x3 es: 320


### Indexación de matrices

NumPy ofrece varias formas de indexar en matrices. La sintaxis estándar de Python `x[obj]` se puede usar para indexar la matriz NumPy, donde `x` es la matriz y `obj` es la selección.

Hay tres tipos de indexación disponibles:

* Acceso al campo

* Recorte básico

* Indexación avanzada

#### Acceso al campo

Si el objeto ndarray es una matriz estructurada, se puede acceder a los campos de la matriz indexando la matriz con cadenas, como un diccionario. La indexación de `x['field-name']` devuelve una nueva vista de la matriz, que tiene la misma dimensión que `x`, excepto cuando el campo es una submatriz  que contiene sólo la parte de los datos en el campo especificado. Los tipos de datos se obtienen con `x.dtype['field-name']`.

In [15]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print(x)

[[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]]


In [16]:
print ("x['a'].shape: ",x['a'].shape)
print ("x['a'].dtype: ", x['a'].dtype)

print ("x['b'].shape: ", x['b'].shape)
print ("x['b'].dtype: ", x['b'].dtype)

x['a'].shape:  (3, 3)
x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64


#### Recorte básico

Las matrices NumPy se pueden dividir, de forma similar a las listas. Debe especificar un segmento para cada dimensión de la matriz, ya que las matrices pueden ser multidimensionales.

La sintaxis de división básica es `i: j: k`, donde `i` es el índice inicial, `j` es el índice final, `k` es el paso y `k` no es igual a 0. Esto selecciona los elementos `m` en la dimensión correspondiente, con valores de índice `, i + k, ...,i + (m - 1)k` donde `m = q + (r distinto de 0)`,  `q` y `r` son el cociente y el resto se obtiene dividiendo `j - i` entre `k`: `j - i = qk + r`, de modo que `i + (m - 1) k < j`.

In [17]:
x = np.array([5, 6, 7, 8, 9])
x[1:7:2]

array([6, 8])

La `k` negativa hace que los pasos vayan hacia índices más pequeños. Los `i` y `j` negativos se interpretan como `n + i` y `n + j` donde `n` es el número de elementos en la dimensión correspondiente.

In [18]:
print (x[-2:5])
print (x[-1:1:-1])

[8 9]
[9 8 7]


Si `n` es el número de elementos en la dimensión que se está recortando. Entonces, si no se proporciona `i`, el valor predeterminado es `0` para  `k > 0` y `n-1` para `k < 0`. Si no se proporciona `j`, el valor predeterminado es `n` para `k > 0` y `-1` para `k < 0`. Si no se proporciona `k`, el valor predeterminado es `1`. Ten en cuenta que `::` es lo mismo que `:` y significa seleccionar todos los índices a lo largo de este eje.

In [19]:
x[4:]

array([9])

Si el número de objetos en la tupla de selección es menor que N , entonces se asume `:` para cualquier dimensión subsiguiente.

In [75]:
# Completar
v1 = np.random.randint(10, size=(3, 4, 5))
v2 = v1[:, 0]
print(v2.shape)

print()

v3 = v1[:, :3]
print(v3.shape)

(3, 5)

(3, 3, 5)


Los puntos suspensivos se expanden al número de : objetos necesarios para hacer una tupla de selección de la misma longitud que `x.ndim`. Solo puede haber una sola elipsis presente.

In [20]:
print(x)

[5 6 7 8 9]


In [21]:
x[...,0]

array(5)

#### Ejercicio

1. Crea una matriz de rango `2` con dimension `(3, 4)`

2. Usa el recorte para extraer la submatriz que consta de las primeras `2` filas y las columnas `1` y `2`.

3. Una parte de una matriz es solo una vista de los mismos datos, comprueba quecualquier modificación modificará la matriz original.



In [22]:
# Tu respuesta

xd=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
dim1=xd.reshape([3,4])
print('Matriz:')
print(dim1)

print()

print (f"Rango matrix: {np.linalg.matrix_rank (xd)}")

print()

print('La submatriz es:')
sub=dim1[:2,:2]
print(sub)

print()

print('Ejemplo de modificación:')
dim1[1:3,1:3]= 0
print(dim1)

Matriz:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Rango matrix: 2

La submatriz es:
[[1 2]
 [5 6]]

Ejemplo de modificación:
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]]


Se puede acceder a la matriz de la fila central de dos maneras.

* Las partes junto con la indexación de enteros darán como resultado una matriz de rango inferior.

* El uso de solo recortes dará como resultado el mismo rango matriz.

In [23]:
# Creamos una matriz de rango 2 array con dimensión (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Dos formas de acceder a los datos en la fila central de la matriz. La combinación de la indexación de enteros con recortes produce una matriz de menor rango, mientras que el uso de solo recortes produce una matriz del mismo rango que la matriz original:

In [24]:
fila_r1 = a[1, :]    # Vista de rango 1 de la segunda fila de a
fila_r2 = a[1:2, :]  # Vista de rango 2 de la segunda fila de a
fila_r3 = a[[1], :]  # Vista de ranfo 2 de la segunda fila de a
print (fila_r1, fila_r1.shape)
print (fila_r2, fila_r2.shape)
print (fila_r3, fila_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


Podemos hacer la misma distinción al acceder a las columnas de una matriz.

In [25]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Indexación avanzada


In [26]:
a = np.array([[1,2], [3, 4]])
#print(a[[0, 1], [0, 1]])

# El ejemplo de indexacion de una matriz entera es equivalente a esto:
# completar

ind=a[1:1]
print(ind)

[]


Al usar la indexacion de un matriz de enteros, puede reutilizar el mismo elemento de la matriz de origen:

In [27]:
print (a[[0, 0], [1, 1]])

# Equivalente al ejemplo de indexacion de matriz de enteros
# completar

[2 2]


Un asunto  importante y extremadamente útil acerca de los recortes de una  matriz es que devuelven  *vistas (`views`)* en lugar de *copias (`copies`)*  de los datos de la matriz. Este es un área en la que NumPy  difiere de la lista de Python:  en las listas, estas son copias.

In [28]:
np.random.seed(0)
x2 = np.random.randint(10, size=(5, 4))
x2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1]])

In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[5 0]
 [7 9]]


In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  0]
 [ 7  9]]


Este comportamiento predeterminado es realmente muy útil: significa que cuando trabajamos con grandes conjuntos de datos, podemos acceder y procesar partes de estos conjuntos de datos sin necesidad de copiar el búfer de datos.

A pesar de las características  de las `vistas` de una  matriz, a veces es útil copiar de forma explícita los datos dentro de una matriz o una submatriz. Esto se puede hacer  con el método `copy()`:

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

In [ ]:
print(x2)

### Reshaping

In [ ]:
x4 = np.arange(1, 10).reshape((3, 3))
print(x4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Ten en cuenta que para que esto funcione, el tamaño de la matriz inicial debe coincidir con el tamaño de la matriz rediseñada. Siempre que sea posible, el método `reshape` utilizará una `vista` sin copia de la matriz inicial.

Otro patrón de `reshaping `, es la conversión de una matriz unidimensional en una fila o columna de una matriz bidimensional. Esto se puede hacer con el método `reshape`  o más fácilmente haciendo uso de `newaxis` dentro de una operación de división:

In [ ]:
x5 = np.array([1, 2, 3])
x5

array([1, 2, 3])

In [ ]:
# vector fila via reshape
# completar

x6= np.array([1,2,3,4])

D = x6.reshape((2,2))
print(D)

[[1 2]
 [3 4]]


In [ ]:
# vector fila con newaxis
# completar

D = x6[np.newaxis, :]
print(D)

[[1 2 3 4]]


In [ ]:
# vector columna via reshape
# completar

B = x6.reshape((-1, 1))
print(B)

[[1]
 [2]
 [3]
 [4]]


In [ ]:
# vector columna con newaxis
# completar

A= x6[:, np.newaxis]
print(A)

[[1]
 [2]
 [3]
 [4]]


### Concatenación y  separación


In [ ]:
x = np.array([4, 5, 6])
y = np.array([7, 8, 9])
np.concatenate([x, y])

array([4, 5, 6, 7, 8, 9])

In [ ]:
# concatenacion de dos o mas matrices
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

In [ ]:
# concatendo una matriz dos veces
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Para trabajar con matrices de distintas dimensiones, se usan las funciones `vstack` y `hstack`:

In [ ]:
x = np.array([0, 1, 2])
grid = np.array([[3, 4, 5],
                 [6, 5, 4]])

# Se junta la matriz de manera vertical
# Completar

np.vstack([x,grid])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 5, 4]])

In [ ]:
# Se junta la matriz de manera horizontal
y = np.array([[23],
              [23]])
# Completar

np.hstack(y)

array([23, 23])

Lo contrario de la concatenación es la división o separación, que es implementado por las funciones `np.split`, `np.hsplit` y `np.vsplit`. Para cada uno de estas funciones , podemos pasar una lista de índices que dan los puntos de división.

Ver:[https://numpy.org/doc/stable/reference/generated/numpy.split.html](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [ ]:
x = [1, 2, 3, 44, 95, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [44 95] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
grid1, grid2 = np.vsplit(grid, [2])
print(grid1)
print(grid2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
grid3, grid4 = np.hsplit(grid,[2])
print(grid3)
print(grid4)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### Fancy


In [29]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [30]:
# Accedemos a tres elementos diferentes
[x[1], x[5], x[2]]

[92, 20, 14]

Alternativamente, podemos pasar una sola lista o matriz de índices para obtener el mismo resultado:

In [31]:
ind = [1,4,8]
x[ind]

array([92, 60, 74])

Cuando se utiliza fancy, la forma del resultado refleja la forma de las matrices de índice en lugar de la forma de la matriz que se indexa y trabaja  en múltiples  dimensiones:

In [32]:
# Completar

arr = np.array([[3, 7],
                [4, 5]])
x[arr]

array([[71, 86],
       [60, 20]])

In [33]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Al igual que con la indexación estándar, el primer índice se refiere a la fila, y el segundo a la columna:

In [34]:
fila = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[fila, col]

array([ 2,  5, 11])

Observa que el primer valor en el resultado es `X[0, 2]`, el segundo es `X[1, 1]`  y el tercero es `X[2, 3]`. El emparejamiento de índices en la indexación fancy  sigue todas las reglas del broadcasting, por ejemplo, si combinamos un vector de columna y un vector de fila dentro de los índices, obtenemos un resultado bidimensional:

In [36]:
# Completar

X[fila[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

Aquí, cada valor de fila se empareja con cada vector de columna, exactamente como se hace en broadcasting  de operaciones aritméticas. Por ejemplo:

In [37]:
# Completar

fila[:, np.newaxis] * col

array([[0, 0, 0],
       [2, 1, 3],
       [4, 2, 6]])

Siempre es importante recordar que en  la indexación fancy, el valor de retorno refleja la forma del broadcasting  de los índices, en lugar de la forma de la matriz que se indexa.

Para operaciones  más potentes, la indexación adornada se puede combinar con los otros esquemas de indexación que existen:

In [39]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
# Combinando el indexado fancy y indices simples
# Completar

X[2, [2, 0, 1]]

array([10,  8,  9])

In [41]:
# Combinando el indexado fancy y el recorte
# Completar

X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

Así como el fancy  se puede utilizar para acceder a partes de una matriz, también se puede utilizar para modificar partes de una matriz. Por ejemplo, si  tenemos una matriz de índices y nos gustaría establecer los elementos correspondientes en una matriz a algún valor, podemos hacer lo siguiente:

In [42]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


Los índices repetidos con estas operaciones pueden causar algunos resultados potencialmente inesperados. Considera lo siguiente:

In [43]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


El resultado de esta operación es asignar primero  `x[0] = 4`, seguido por `x[0] = 6`. Pero el resultado es que `x[0]` contiene el valor 6.

Considera la siguiente operación:

In [44]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

En este caso algún resultado inesperado se debe conceptualmente  a que `x[i] +=1` se entiende como una abreviatura de `x[i] = x [i] + 1`. Cuando `x[i] + 1` es evaluado el resultado es asignado  a los índices en `x` . Con esto en mente, no es que el aumento que ocurre varias veces, sino la asignación, que conduce a los resultados  no intuitivos.

Si quieremos  el otro comportamiento donde se repite la operación, se puede utilizar el método `at()` de `ufuncs`:

In [47]:
# Completar

xd2 = np.zeros(8)
np.add.at(xd2, i, 1)
print(xd2)

[0. 0. 1. 2. 3. 0. 0. 0.]


El método `at()` realiza una aplicación  del operador dado en los índices especificados (aquí, `i`) con el valor especificado (aquí, `1`).

###  Expresiones vectorizadas

### Agregaciones


In [48]:
L = np.random.random(100)
sum(L)

47.03631196196963

La sintaxis es bastante similar a la función de `sum` de  `NumPy`  y el resultado es el mismo en el caso más simple:

In [49]:
np.sum(L)

47.03631196196964

Sin embargo, debido a que la operación se ejecuta  en código compilado, la versión `NumPy` de la operación se calcula mucho más rápidamente:

In [50]:
matriz_grande = np.random.rand(1000000)
%timeit sum(matriz_grande)
%timeit np.sum(matriz_grande)

108 ms ± 28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
398 µs ± 16.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


La función `sum` y la función `np.sum` no son idénticas, lo que a veces puede conducir a la confusión.  En particular, sus argumentos opcionales tienen significados diferentes  y `np.sum` es válido a  varias dimensiones de una matriz.

In [51]:
# Otras funciones min y max
min(matriz_grande), max(matriz_grande)

(7.071203171893359e-07, 0.9999997207656334)

In [52]:
%timeit min(matriz_grande)
%timeit np.min(matriz_grande)

83.6 ms ± 25.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
447 µs ± 11.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Todas estas funciones también están disponibles como métodos en la clase `ndarray`. Por ejemplo, `np.mean(data)` y `data.mean()` en el ejemplo siguiente son equivalentes:

In [53]:
data = np.random.normal(size=(15, 15))
np.mean(data)

0.044126718568646986

In [54]:
data.mean()

0.044126718568646986

Un tipo común de operación de agregación es un agregado a lo largo de una fila o columna.

In [55]:
M = np.random.random((5, 6))
print(M)

[[0.78911301 0.63111867 0.7285163  0.66979703 0.17088322 0.13881003]
 [0.00935403 0.63751707 0.76420221 0.1876222  0.95137218 0.44469986]
 [0.47577551 0.43077223 0.49532871 0.58341548 0.27654054 0.96025749]
 [0.12685672 0.38686572 0.29660634 0.99907694 0.00377931 0.82984241]
 [0.75816216 0.01685189 0.23811077 0.28054238 0.63922302 0.31781681]]


De forma predeterminada, cada función de agregación de  `NumPy`  devolverá el agregado sobre toda la matriz:

In [56]:
M.sum()

14.238830244406318

Las funciones de agregación toman un argumento adicional que especifica el eje a lo largo del cual se calcula el agregado. Por ejemplo, podemos encontrar el valor de la suma y el  mínimo de cada columna especificando `axis = 0`:

In [57]:
M.sum(axis= 0)

array([2.15926144, 2.10312558, 2.52276433, 2.72045403, 2.04179827,
       2.69142659])

In [58]:
data = np.random.normal(size=(5, 10, 15))
data.sum(axis=0).shape

(10, 15)

In [59]:
data.sum(axis=(0, 2)).shape

(10,)

In [60]:
data.sum()

-40.96575138792459

Algunas funciones de agregación en `Numpy ` son :


|Nombre de funcion  | VersionNaN-safe     | Descripcion                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Calcula suma de elementos                     |
| ``np.prod``       | ``np.nanprod``      | Calcula el producto de elementos              |
| ``np.mean``       | ``np.nanmean``      | Calcula la media de elementos                 |
| ``np.std``        | ``np.nanstd``       | Calcula la desviacion estandar                |
| ``np.var``        | ``np.nanvar``       | Calcula la  varianza                          |
| ``np.min``        | ``np.nanmin``       | Encuentra el minimo valor                     |
| ``np.max``        | ``np.nanmax``       | Encuentra el maximo valor                     |
| ``np.argmin``     | ``np.nanargmin``    | Encuenta el index del minimo valor            |
| ``np.argmax``     | ``np.nanargmax``    | Encuentra el index del maximo valor           |
| ``np.median``     | ``np.nanmedian``    | Calcula la mediana de elementos               |
| ``np.percentile`` | ``np.nanpercentile``| Calcula el rango estatistico de elementos     |
| ``np.any``        | N/A                 | Evalua si algun elemento es true              |
| ``np.all``        | N/A                 | Evalua si todos los elementos son true        |



#### Broadcasting


In [61]:
a = np.array([0, 1, 2])
b = np.array([2, 6, 1])
a + b

array([2, 7, 3])

El  `broadcasting` permite que estos tipos de operaciones binarias se realicen en matrices de diferentes tamaños; por ejemplo, podemos añadir  un escalar (una matriz de dimensión cero) a una matriz:

In [62]:
a + 5


array([5, 6, 7])

Podemos extender de manera similar esto a matrices de mayor dimensión. Veamos el resultado cuando agregamos una matriz unidimensional a una matriz bidimensional:

In [63]:
A = np.arange(16).reshape(4, 4)
b = np.arange(4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
A + b

Podemos aplicar el  `broadcasting` en dos matrices. Considere el siguiente ejemplo:

In [76]:
# Completar

mult = A * b

print(mult)

[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]
 [ 0 13 28 45]]


In [82]:
# Completar

sum = A + b
print(sum)

[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]]


In [84]:
# Completar

mod= A % b
print(mod)

[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 2]
 [0 0 0 0]]


<ipython-input-84-15653bbad5b6>:3: RuntimeWarning: divide by zero encountered in remainder
  mod= A % b


In [85]:
# Completar

ent= A//b
print(ent)

[[ 0  1  1  1]
 [ 0  5  3  2]
 [ 0  9  5  3]
 [ 0 13  7  5]]


<ipython-input-85-4206bbce0edc>:3: RuntimeWarning: divide by zero encountered in floor_divide
  ent= A//b


###  Regla del broadcasting

El `broadcasting` en `NumPy` sigue un estricto conjunto de reglas para determinar la interacción entre dos matrices :

* Regla 1: Si las dos matrices difieren en su número de dimensiones, la forma de la matriz que tiene menos dimensiones se rellena con unos en el lado principal (izquierdo).

* Regla 2: Si la forma de los dos matrices no coincide con ninguna dimensión, la matriz con la forma igual a 1 en esa dimensión se estira para que coincida con la otra dimensión.

* Regla 3: Si en cualquier dimensión los tamaños son distintos y ninguno es igual a 1, se genera un error.

### Un útil truco:

In [64]:
J = np.arange(0, 40, 10)
J.shape

(4,)

In [65]:
J = J[:, np.newaxis]  # agregamos un nuevo eje ->  matriz 2D
J.shape

(4, 1)

In [66]:
J

array([[ 0],
       [10],
       [20],
       [30]])

In [67]:
J + 3

array([[ 3],
       [13],
       [23],
       [33]])

### Comparaciones, máscaras y lógica Booleana


In [ ]:
a1 = np.array([1, 2, 3, 4])
b1 = np.array([4, 3, 2, 1])
a1 < b1

In [ ]:
np.all(a1 < b1)

In [ ]:
np.any(a1 < b1)

In [ ]:
if np.all(a1 < b1):
    print(" Todos los elementos en a1 son menores que los elementos en b1 ")
elif np.any(a1 < b1):
    print("Algunos elementos en a1 son menores que los elementos de b1")
else:
    print("Todos los elementos en b1 son menores que los elementos de a1")

Al aparecer en una expresión aritmética junto con un número escalar, u otra matriz `NumPy` con un tipo de datos numéricos, una matriz booleana se convierte en una matriz numérica con valores `0` y `1` en lugar de `False` y `True`, respectivamente.

In [ ]:
# Completar

In [ ]:
# Completar

In [ ]:
# Completar

Esta es una propiedad útil para la computación condicional, como cuando se definen funciones.

In [ ]:
#def pulso(t, posicion, altura, ancho):
#    return altura * (t >= posicion) * (t <= (posicion + ancho))
# Completar

### Matrices booleanas como máscaras

Revisar: [masked array](https://docs.scipy.org/doc/numpy/reference/maskedarray.html).

In [ ]:
k = np.array([1, 3, -1, 5, 7, -1])
mask = (k < 0)
mask

In [ ]:
# Un ejemplo bidimensional
rng = np.random.RandomState(0)
z1 = rng.randint(10, size=(3, 4))
z1

In [ ]:
# Completar

Ahora, para seleccionar estos valores de la matriz, podemos simplemente indexar en esta matriz booleana, esto se conoce como una operación de `enmascaramiento`:

In [ ]:
# Completar

El siguiente ejemplo muestra cómo sumar la matriz de enmascaramiento,  donde `True` representa uno y `False` representa 0.

In [ ]:
# Completar

### Lectura recomendada: [Numpy Reference](https://docs.scipy.org/doc/numpy/reference/).